#coding=utf-8
'''
Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, …
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def fibs():
    a = 1
    b = 2
    while True:
        a,b = b,a+b
        yield b

result = 2
count = 2
bound = 4000000

for i in fibs():
    count += 1
    if i <= bound:
        if (count+1)%3 == 0:
            result += i
    else:
        break
print result


